spring:
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
jpa.open-in-view: false

server.port: 8080

spring.datasource:
  url: jdbc:mysql://localhost:3306/game?serverTimezone=UTC
  username: root
  password: 1707Gleb
